export { ReactComponent as MenuIcon } from "./menu.svg";
export { ReactComponent as CloseIcon } from "./close.svg";
export { ReactComponent as DisplayIcon } from "./display.svg";
export { ReactComponent as MobileIcon } from "./mobile.svg";
export { ReactComponent as NotebookIcon } from "./notebook.svg";
export { ReactComponent as BagIcon } from "./bag.svg";
export { ReactComponent as ArrowIcon } from "./arrow.svg";
export { ReactComponent as AllIcon } from "./all.svg";
export { ReactComponent as Star } from "./star.svg";